# Generated by Django 2.2.4 on 2019-09-05 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amsuser', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='amsuser',
            options={'verbose_name': 'ams 사용자', 'verbose_name_plural': '사용자'},
        ),
    ]
